A4.exe: driver.o DoublyLinkedList.o LinkedList.o LinkedNode.o Node.o 
	g++ driver.o DoublyLinkedList.o LinkedList.o LinkedNode.o Node.o -o A4.exe
	
driver.o:
	g++ -c driver.cpp -o driver.o
	
DoublyLinkedList.o:
	g++ -c DoublyLinkedList.cpp -o DoublyLinkedList.o
	
LinkedList.o:
	g++ -c LinkedList.cpp -o LinkedList.o
	
LinkedNode.o:
	g++ -c LinkedNode.cpp -o LinkedNode.o
	
node.o:
	g++ -c Node.cpp -o Node.o
	
clean:
	rm *.o A4.exe